#mysql connection from mamp
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: validation
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:21785/railway
    username: root
    password: MtXNEqZCyilCAgueDJqnIGAagWvcXklm
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret-key: goodsecret


