#mysql connection from mamp
spring:
  application:
    name: validation
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:21785/railway
    username: root
    password: MtXNEqZCyilCAgueDJqnIGAagWvcXklm
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret-key: goodsecret

