#mysql connection from mamp
spring:
  application:
    name: validation
  datasource:
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11701172
    username: sql11701172
    password: iMXl3AGsnp
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret-key: goodsecret