#mysql connection from mamp
spring:
  application:
    name: validation
  datasource:
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11701187
    username: sql11701187
    password: WwSJKpeiXu
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret-key: goodsecret


server:
  port: 8080